"""
Django settings for hardware project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

STRIPE_API_KEY = os.environ.get('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')
#STRIPE_ENDPOINT_SECRET = os.environ.get('we_1NdrENFGUL8ZqC3OCmP2Z1fJ')
STRIPE_ENDPOINT_SECRET = os.environ.get('whsec_E701uIyWx8m5KfcDh6PUn6HYxAPUR5Dh')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hardwarefyitest@gmail.com'
EMAIL_HOST_PASSWORD = 'Unripe1343Lemon'
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(o#@d&z&%eaxk_^34@nobq81ghj3+h%fpqjf!$@8gsrw&k5xhd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['hardwarefyi.com', 'www.hardwarefyi.com','app.hardwarefyi.com', 'www.app.hardwarefyi.com','https://checkout.stripe.com/c/pay/cs_live_b1aOi4DOpxONxRAMV31l0D0WEgQj88PgEoasFlZ9rnQVWxwWNlqJiw2Itl#fidkdWxOYHwnPyd1blppbHNgWjA0TUpxVj1DQlBJPV90RjZKa1d9XExENElgSD1TUlY2NVVIM0pOf2F2TmxfYFw8QX9TYkZfMUdXM29TZ3E2NjBOX2NvRlJcUW5jf2BEYkp2Vms1cTVSdldJNTVLf0NqaX9ccicpJ3VpbGtuQH11anZgYUxhJz8nYFNkZlRINElXMF1nM0Q1YVRWJyknd2BjYHd3YHdKd2xibGsnPydtcXF1dj8qKnJycittZHdhcmR3YGN8bCtmamgqJ3gl']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hardware.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hardware.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

